version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: algafood_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - algafood_data:/var/lib/mysql

volumes:
  algafood_data: